#!/bin/sh

# From the repository root copy the post-commit script to .git/hooks/
#
#   $ cp git-hooks/post-commit .git/hooks/
#
#  Then make the post-commit file executable with:
#
#   $ chmod u+x .git/hooks/post-commit
#

git-secrets --scan -r
