apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rails
  labels:
    app: rails
spec:
  replicas: 1
  # revisionHistoryLimit: 1
  # minReadySeconds: 10
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 1
  selector:
    matchLabels:
      app: rails-container
  template:
    metadata:
      labels:
        app: rails-container
    spec:
      containers:
      - name: rails
        image: beccapearce/parliamentary-questions_web:latest
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', "bundle exec rake db:setup && bundle exec rake user:create &&  bundle exec rake 'user:create[admin@admin.com, 123456789, admin]' && bundle exec rails s"]
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: shared-environment
      - name: postgres-container
        image: 'postgres:9.6.6'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: shared-environment
        volumeMounts:
          - name: postgres-volume-mount
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pvc
