# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-pvc
#   labels:
#     type: local
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi
#   volumeName: postgres-pv

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: postgres-pvc
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
