apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: parliamentary-questions
  name: rails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parliamentary-questions
  template:
    metadata:
      labels:
        app: parliamentary-questions
    spec:
      containers:
        -
          command:
            - sh
            - "-c"
            - "bundle exec rails s"
          envFrom:
            -
              configMapRef:
                name: environment-variables
            -
              secretRef:
                name: pq-secrets
          image: "beccapearce/parliamentary-questions_web:latest"
          imagePullPolicy: IfNotPresent
          name: parliamentary-questions-rails-app
          ports:
            -
              containerPort: 3000
        -
          envFrom:
            -
              configMapRef:
                name: environment-variables
            -
              secretRef:
                name: pq-secrets
          image: "postgres:10"
          imagePullPolicy: IfNotPresent
          name: postgres
          ports:
            -
              containerPort: 5432
          volumeMounts:
            -
              mountPath: /var/lib/postgresql/data
              name: postgres-volume-mount
      volumes:
        -
          name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pvc
