apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nightly-import
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            -
              command:
                - sh
                - "-c"
                - "bundle exec rake 'pqa:nightly_import'"
              envFrom:
                -
                  configMapRef:
                    name: environment-variables
                -
                  secretRef:
                    name: pq-secrets
              image: "beccapearce/parliamentary-questions_web:latest"
              imagePullPolicy: IfNotPresent
              name: nightly-import
          restartPolicy: OnFailure
  schedule: "0 4 * * *"
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 3

# -----------------------------------------------------------------------------

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nightly-import
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            -
              command:
                - sh
                - "-c"
                - "bundle exec rake 'pqa:nightly_import'"
              envFrom:
                -
                  configMapRef:
                    name: environment-variables
                -
                  secretRef:
                    name: pq-secrets
              image: "beccapearce/parliamentary-questions_web:latest"
              imagePullPolicy: IfNotPresent
              name: nightly-import
          restartPolicy: OnFailure
  schedule: "0 6 * * *"
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 3
