apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: postgres-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/postgres-pv
  storageClassName: standard
