version: "2"

plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: "rubocop-0-92"
exclude_paths:
- config/
- db/
- spec/
- vendor/
- "app/assets/javascripts/bootstrap.js"
- "app/assets/javascripts/jquery.datetimepicker.js"
- "app/assets/javascripts/moment.js"
- "app/assets/javascripts/chart.js"
- "lib/gecko_report.rb"
