# A cronjob to clear the database before the nightly import is run.
# This is to avoid overloading the database with too many questions
# which are not progessed or closed and so stagnate in the database
# in our test environments.

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clear-database
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            -
              command:
                - sh
                - "-c"
                - "bundle exec rake db:setup && bundle exec rake user:create && bundle exec rake 'user:create[admin@admin.com, 123456789, admin]'"
              env:
                -
                  name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      key: rds_instance_address
                      name: parliamentary-questions-development-rds
                -
                  name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      key: database_username
                      name: parliamentary-questions-development-rds
                -
                  name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database_password
                      name: parliamentary-questions-development-rds
              envFrom:
                -
                  configMapRef:
                    name: environment-variables
                -
                  secretRef:
                    name: pq-secrets
              image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/pq-team/parliamentary-questions:latest"
              imagePullPolicy: IfNotPresent
              name: clear-database
          restartPolicy: OnFailure
  schedule: "* 3 * * *"
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 3
