# A cronjob to clear the database before the nightly import is run.
# This is to avoid overloading the database with too many questions
# which are not progessed or closed and so stagnate in the database
# in our test environments.

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clear-database
spec:
  schedule: "* 3 * * *"
  startingDeadlineSeconds: 10
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clear-database
            image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/pq-team/parliamentary-questions:latest
            imagePullPolicy: IfNotPresent
            command: ['sh', '-c', "bundle exec rake db:setup  && bundle exec rake user:create &&  bundle exec rake 'user:create[admin@admin.com, 123456789, admin]'"]
            envFrom:
              - configMapRef:
                  name: environment-variables
              - secretRef:
                  name: pq-secrets
            env:
              - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: parliamentary-questions-development-rds
                    key: rds_instance_address
              - name: PGUSER
                valueFrom:
                  secretKeyRef:
                    name: parliamentary-questions-development-rds
                    key: database_username
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: parliamentary-questions-development-rds
                    key: database_password
          restartPolicy: OnFailure
