apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pq-development
  namespace: parliamentary-questions-development
spec:
  rules:
    - host: development.trackparliamentaryquestions.service.gov.uk
      http:
        paths:
          - backend:
              serviceName: parliamentary-questions-service
              servicePort: 3000
            path: /
  tls:
    - hosts:
        - development.trackparliamentaryquestions.service.gov.uk
      secretName: parliamentary-questions-development-cert
