apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: parliamentary-questions-ingress
spec:
  tls:
  - hosts:
    - parliamentary-questions.apps.live-1.cloud-platform.service.justice.gov.uk
  rules:
  - host: parliamentary-questions.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: parliamentary-questions-service
          servicePort: 3000
