apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: parliamentary-questions
  namespace: parliamentary-questions-production
spec:
  rules:
    - host: trackparliamentaryquestions.service.gov.uk
      http:
        paths:
          - backend:
              serviceName: parliamentary-questions-service
              servicePort: 3000
            path: /
  tls:
    - hosts:
        - trackparliamentaryquestions.service.gov.uk
      secretName: parliamentary-questions-production-cert
