apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: parliamentary-questions
  namespace: parliamentary-questions-production
  annotations:
    kubernetes.io/ingress.class: "modsec01"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
    external-dns.alpha.kubernetes.io/set-identifier: parliamentary-questions-parliamentary-questions-production-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  rules:
    - host: trackparliamentaryquestions.service.gov.uk
      http:
        paths:
          - backend:
              serviceName: parliamentary-questions-service
              servicePort: 3000
            path: /
  tls:
    - hosts:
        - trackparliamentaryquestions.service.gov.uk
      secretName: parliamentary-questions-production-cert
 