Rails.application.config.assets.precompile += %w( favicon.ico )
Rails.application.config.assets.precompile += %w( apple-touch-icon-152x152.png )
Rails.application.config.assets.precompile += %w( apple-touch-icon-120x120.png )
Rails.application.config.assets.precompile += %w( apple-touch-icon-76x76.png )
Rails.application.config.assets.precompile += %w( apple-touch-icon-60x60.png )
Rails.application.config.assets.precompile += %w( opengraph-image.png )
Rails.application.config.assets.precompile += %w( gov.uk_logotype_crown.png )
Rails.application.config.assets.precompile += %w(.svg .eot .woff .ttf *.js ^[^_]*.css)
