default: &default
  adapter: postgresql

development:
  database: parliamentary_questions_dev
  <<: *default
test:
  database: parliamentary_questions_test
  <<: *default
production:
  adapter: postgresql
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] || 'parliamentary-questions' %>
  pool: 15
