
development:
  adapter: postgresql
  encoding: unicode
  database: parliamentary-questions_dev
  host: localhost
  pool: 10


test: &test
  adapter: postgresql
  encoding: unicode
  database: parliamentary-questions_test
  host: localhost
  pool: 10

production:
  adapter: postgresql
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] || 'parliamentary-questions' %>
  pool: 15

cucumber:
  <<: *test
