mail_from: PQ Team <no-reply@trackparliamentaryquestions.service.gov.uk>
mail_reply_to: pqs@justice.gsi.gov.uk
mail_tech_support: pqsupport@digital.justice.gov.uk
http_client_timeout: 20
commission_mail_from: PQ Team <no-reply@trackparliamentaryquestions.service.gov.uk>
healthcheck_pqa_api_interval: 15               # minimum interval between pqa API healthchecks in minutes


excepted_from_ssl:
  - ping.json

mail_worker:
  pid_filepath: '/tmp/mail_worker.pid'
  max_fail_count: 15
  timeout: 300

