live_url: https://trackparliamentaryquestions.service.gov.uk
mail_from: PQ Team <no-reply@trackparliamentaryquestions.service.gov.uk>
mail_reply_to: pqs@justice.gov.uk
mail_tech_support: pqsupport@digital.justice.gov.uk
http_client_timeout: 20
commission_mail_from: PQ Team <no-reply@trackparliamentaryquestions.service.gov.uk>
healthcheck_pqa_api_interval: 15               # minimum interval between pqa API healthchecks in minutes
key_metric_threshold: 0.5
parliamentary_team_email: 6914dbfe-4cbb-46dc-aaac-c4be561c8e72
tech_support_email: 0cdb6fb9-ded7-4fd6-b878-2c431bcb924f
govuk_notify_api_key: refer-to-instructions-on-how-to-add-key-to-env-variables

excepted_from_ssl:
  - ping.json

mail_worker:
  pid_filepath: '/tmp/mail_worker.pid'
  max_fail_count: 15
  timeout: 300

gecko_warning_levels:
  num_emails_waiting: 15
  num_emails_abandoned: 1
  pctg_answered_tokens: 50

smoke_test_runner:
  out_file: '/tmp/smoke_test_run'
