apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pq-staging
  namespace: parliamentary-questions-staging
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: pq-secrets
    external-dns.alpha.kubernetes.io/set-identifier: pq-staging-parliamentary-questions-staging-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  ingressClassName: default
  rules:
    - host: staging.trackparliamentaryquestions.service.gov.uk
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: parliamentary-questions-service
              port: 
                number: 3000
  tls:
    - hosts:
        - staging.trackparliamentaryquestions.service.gov.uk
      secretName: parliamentary-questions-staging-cert
