apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pq-staging
  namespace: parliamentary-questions-staging
spec:
  rules:
    - host: staging.trackparliamentaryquestions.service.gov.uk
      http:
        paths:
          - backend:
              serviceName: parliamentary-questions-service
              servicePort: 3000
            path: /
  tls:
    - hosts:
        - staging.trackparliamentaryquestions.service.gov.uk
      secretName: parliamentary-questions-staging-cert
