apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: parliamentary-questions
  namespace: parliamentary-questions-staging
spec:
  rules:
    - host: parliamentary-questions-staging.apps.live-1.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - backend:
              serviceName: parliamentary-questions-service
              servicePort: 3000
            path: /
  tls:
    - hosts:
        - parliamentary-questions-staging.apps.live-1.cloud-platform.service.justice.gov.uk
