apiVersion: batch/v1
kind: Job
metadata:
  name: rails-migrations
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        -
          command:
            - sh
            - "-c"
            - "bundle exec rake db:setup]'"
          env:
            -
              name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: rds_instance_address
                  name: parliamentary-questions-staging-rds
            -
              name: PGUSER
              valueFrom:
                secretKeyRef:
                  key: database_username
                  name: parliamentary-questions-staging-rds
            -
              name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: database_password
                  name: parliamentary-questions-staging-rds
            - 
              name: GOVUK_NOTIFY_API_KEY
              valueFrom: 
                secretKeyRef:
                  key: GOVUK_NOTIFY_API_KEY     
                  name: pq-secrets    
          envFrom:
            -
              configMapRef:
                name: environment-variables
            -
              secretRef:
                name: pq-secrets
          image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/pq-team/parliamentary-questions:latest"
          imagePullPolicy: Always
          name: parliamentary-questions-rails-app
      restartPolicy: OnFailure
