name: CI Workflow
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove image-bundled Chrome
        run: sudo apt-get purge google-chrome-stable

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@c785b87e244131f27c9f19c1a33e2ead956ab7ce # v1.7.3
        with:
          chrome-version: 128
          install-chromedriver: true

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Lint Ruby files
        run: bundle exec rubocop

      - name: Security audit application code
        run: bundle exec brakeman -q

  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write

    strategy:
      fail-fast: false
      matrix:
        ci_total_jobs: [4]
        ci_job_index: ["0", "1", "2", "3"]

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1"
      PQ_REST_API_HOST: http://localhost:8888
      CI: true
      CI_TOTAL_JOBS: ${{ matrix.ci_total_jobs }}
      CI_JOB_INDEX: ${{ matrix.ci_job_index }}

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install packages
        run: yarn install --pure-lockfile

      - name: Precompile assets
        run: bin/rails assets:precompile

      - name: Setup test database
        run: bin/rails db:setup

      - name: Run unit and feature tests
        run: bundle exec parallel_rspec -n "${CI_TOTAL_JOBS}" --only-group "${CI_JOB_INDEX}" --group-by "runtime"

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: coverage-${{env.CI_JOB_INDEX}}
          path: coverage/.resultset.json

  coverage:
    needs: test
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove image-bundled Chrome
        run: sudo apt-get purge google-chrome-stable

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@c785b87e244131f27c9f19c1a33e2ead956ab7ce # v1.7.3
        with:
          chrome-version: 128
          install-chromedriver: true

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          path: coverage

      - name: Collate coverage
        run: bundle exec rake coverage:report

      - name: Code coverage
        uses: joshmfrankel/simplecov-check-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_suite_coverage: 84
          minimum_file_coverage: 100

  build-and-deploy:
    needs: [linting, coverage]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
